### ISSUE TITLE
A mechanism to change the pin status of the NotifyIcon

### ISSUE THREAD

**Issue by maxpavlov** [Zumwani/ShellUtility#1]
Hello. Wonderful wrapper around the NotifyIcons in shell, with nicely handled callback and overall interop part. I wonder if this is possible to extend the code to allow changing the Pin status of the icon, for instance changing from "when active" to "pinned"? Is it technically possible with the code infrastructure in the repo, or an implementation of this would be complex addition? Thanks.

**Comment by Zumwani** [comment]
Hi, it's been a while since I worked on it, so I can't remember how much work it would be to implement.  I did however decide to not implement this in this library (and did as such not look too closely at it), since that could override the users preferences against their will, which may or may not be a big deal, but I did decide to just not worry about it by not implementing it.

Feel free to fork this repo though if you are able to figure it out :D
